    package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class ArrayOfProcesoAutenticacionCapturaHuella extends Vector< ProcesoAutenticacionCapturaHuella> implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{
    private transient java.lang.Object __source;

   public ArrayOfProcesoAutenticacionCapturaHuella()
   {
   }
    public void loadFromSoap(java.lang.Object inObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        __source=inObj;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                ProcesoAutenticacionCapturaHuella j1= (ProcesoAutenticacionCapturaHuella)__envelope.get(j,ProcesoAutenticacionCapturaHuella.class,false);
                add(j1);
            }
        }
}
    public java.lang.Object getSourceObject()
    {
        return __source;
    }
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "ProcesoAutenticacionCapturaHuella";
        info.type = ProcesoAutenticacionCapturaHuella.class;
    	info.namespace= "http://casb.bytte.com.co/";
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

    


    protected ArrayOfProcesoAutenticacionCapturaHuella(android.os.Parcel parcel)
    {
        for (Object obj:parcel.readArray(this.getClass().getClassLoader()) )
        {
            this.add((ProcesoAutenticacionCapturaHuella) obj);
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        parcel.writeArray(this.toArray());
    }

    public static final Creator< ArrayOfProcesoAutenticacionCapturaHuella> CREATOR = new Creator< ArrayOfProcesoAutenticacionCapturaHuella>() {
            @Override
            public ArrayOfProcesoAutenticacionCapturaHuella createFromParcel(android.os.Parcel in) {
                return new ArrayOfProcesoAutenticacionCapturaHuella(in);
            }

            @Override
            public ArrayOfProcesoAutenticacionCapturaHuella[] newArray(int size) {
                return new ArrayOfProcesoAutenticacionCapturaHuella[size];
            }
        };}