package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class AutenticacionDactilarRequest extends RequestBase implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public ArrayOfProcesoAutenticacionCapturaHuella HuellasProceso;
    
    public Integer ScoreRequerido=0;
    
    public Integer HuellasAProcesar=0;
    

    public AutenticacionDactilarRequest()
    {
    }
    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("HuellasProceso"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)__envelope.get(j,ArrayOfProcesoAutenticacionCapturaHuella.class,false);
            }
            return true;
        }
        if (info.name.equals("ScoreRequerido"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreRequerido = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreRequerido = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("HuellasAProcesar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.HuellasAProcesar = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.HuellasAProcesar = (Integer)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.HuellasProceso!=null?this.HuellasProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return ScoreRequerido;
        }
        if(propertyIndex==count+2)
        {
            return HuellasAProcesar;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "HuellasProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreRequerido";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "HuellasAProcesar";
            info.namespace= "http://casb.bytte.com.co/";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected AutenticacionDactilarRequest(android.os.Parcel parcel)
    {
        super(parcel);
        this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)parcel.readValue(this.getClass().getClassLoader());
        this.ScoreRequerido = (Integer)parcel.readValue(null);
        this.HuellasAProcesar = (Integer)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        super.writeToParcel(parcel, flags);
        parcel.writeValue(this.HuellasProceso);
        parcel.writeValue(this.ScoreRequerido);
        parcel.writeValue(this.HuellasAProcesar);
    }

    public static final Creator< AutenticacionDactilarRequest> CREATOR = new Creator< AutenticacionDactilarRequest>() {
            @Override
            public AutenticacionDactilarRequest createFromParcel(android.os.Parcel in) {
                return new AutenticacionDactilarRequest(in);
            }

            @Override
            public AutenticacionDactilarRequest[] newArray(int size) {
                return new AutenticacionDactilarRequest[size];
            }
        };    
}

