package com.trantec.yo.services.bytte.authentication;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class CASB_x002E_ProcesoAutenticacionService
{
    interface IWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="https://portal.bytte.com.co/casb/YoPrestoPR/CASB.ProcesoAutenticacion/Service/ServicioAutenticacion.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    public boolean enableLogging;
    public boolean createClassesForAny = false;

    public CASB_x002E_ProcesoAutenticacionService(){}

    public CASB_x002E_ProcesoAutenticacionService(String url)
    {
        this.url = url;
    }

    public CASB_x002E_ProcesoAutenticacionService(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
            envelope.createClassesForAny = createClassesForAny;
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }  
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public ProcesoAutenticacionLogResponse ConsultaProcesoValidacionDocumento(final ConsultaProcesoValidacionDocumentoRequest request ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ProcesoAutenticacionLogResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://casb.bytte.com.co/","request",new ConsultaProcesoValidacionDocumentoRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ConsultaProcesoValidacionDocumento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="request";
                __info.type=ConsultaProcesoValidacionDocumentoRequest.class;
                __info.setValue(request!=null?request:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ProcesoAutenticacionLogResponse)getResult(ProcesoAutenticacionLogResponse.class,__result,"ConsultaProcesoValidacionDocumentoResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ConsultaProcesoValidacionDocumento",__profile);
    }
    
    public ProcesoAutenticacionLogResponse ConsultaProcesoValidacionDocumentoWSQ(final ConsultaProcesoValidacionDocumentoRequest request ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ProcesoAutenticacionLogResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://casb.bytte.com.co/","request",new ConsultaProcesoValidacionDocumentoRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ConsultaProcesoValidacionDocumentoWSQ");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="request";
                __info.type=ConsultaProcesoValidacionDocumentoRequest.class;
                __info.setValue(request!=null?request:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ProcesoAutenticacionLogResponse)getResult(ProcesoAutenticacionLogResponse.class,__result,"ConsultaProcesoValidacionDocumentoWSQResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ConsultaProcesoValidacionDocumentoWSQ",__profile);
    }
    
    public ProcesoANIResponse ProcesoConsultaANI(final ProcesoANIRequest request ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ProcesoANIResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://casb.bytte.com.co/","request",new ProcesoANIRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ProcesoConsultaANI");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="request";
                __info.type=ProcesoANIRequest.class;
                __info.setValue(request!=null?request:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ProcesoANIResponse)getResult(ProcesoANIResponse.class,__result,"ProcesoConsultaANIResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ProcesoConsultaANI",__profile);
    }
    
    public ConvertClienteResponse ConversionCodigodeBarras(final String barCodeBase64 ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ConvertClienteResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ConversionCodigodeBarras");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="barCodeBase64";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(barCodeBase64!=null?barCodeBase64:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ConvertClienteResponse)getResult(ConvertClienteResponse.class,__result,"ConversionCodigodeBarrasResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ConversionCodigodeBarras",__profile);
    }
    
    public ProcesoValidacionDocumentoResponse ValidacionEnrolamientoDocumento(final ValidacionEnrolamientoDocumentoRequest request ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ProcesoValidacionDocumentoResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://casb.bytte.com.co/","request",new ValidacionEnrolamientoDocumentoRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ValidacionEnrolamientoDocumento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="request";
                __info.type=ValidacionEnrolamientoDocumentoRequest.class;
                __info.setValue(request!=null?request:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ProcesoValidacionDocumentoResponse)getResult(ProcesoValidacionDocumentoResponse.class,__result,"ValidacionEnrolamientoDocumentoResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ValidacionEnrolamientoDocumento",__profile);
    }
    
    public ProcesoValidacionDocumentoResponse AutenticacionDactilar(final AutenticacionDactilarRequest request ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ProcesoValidacionDocumentoResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://casb.bytte.com.co/","request",new AutenticacionDactilarRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "AutenticacionDactilar");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="request";
                __info.type=AutenticacionDactilarRequest.class;
                __info.setValue(request!=null?request:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ProcesoValidacionDocumentoResponse)getResult(ProcesoValidacionDocumentoResponse.class,__result,"AutenticacionDactilarResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/AutenticacionDactilar",__profile);
    }
    
    public UsuarioResponse ConsultaUsuario(final String NumeroDocumento ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (UsuarioResponse)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://casb.bytte.com.co/", "ConsultaUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://casb.bytte.com.co/";
                __info.name="NumeroDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(NumeroDocumento!=null?NumeroDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (UsuarioResponse)getResult(UsuarioResponse.class,__result,"ConsultaUsuarioResult",__envelope);
            }
        },"http://casb.bytte.com.co/IServicioAutenticacion/ConsultaUsuario",__profile);
    }

    
    protected java.lang.Object execute(IWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    System.out.println("requestDump: "+__httpTransport.requestDump);
                    
                }
                if (__httpTransport.responseDump != null) {
                    System.out.println("responseDump: "+__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
        
    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;

        return newException;
    }
}


