package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ProcesoAutenticacionCapturaHuella extends AttributeContainer implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public byte[] Imagen;
    
    public byte[] WSQImagen;
    
    public String Template;
    
    public Integer TemplateVersion=0;
    
    public Integer IdFingerprint=0;
    
    public String URL;
    private transient java.lang.Object __source;    
    

    public ProcesoAutenticacionCapturaHuella()
    {
    }
    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Imagen"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Imagen = Helper.getBinary(j,false);
            }
            return true;
        }
        if (info.name.equals("WSQImagen"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WSQImagen = Helper.getBinary(j,false);
            }
            return true;
        }
        if (info.name.equals("Template"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Template = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Template = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TemplateVersion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TemplateVersion = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.TemplateVersion = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdFingerprint"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdFingerprint = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdFingerprint = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("URL"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.URL = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.URL = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Imagen!=null?org.kobjects.base64.Base64.encode((byte[])this.Imagen):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.WSQImagen!=null?org.kobjects.base64.Base64.encode((byte[])this.WSQImagen):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Template!=null?this.Template:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return TemplateVersion;
        }
        if(propertyIndex==4)
        {
            return IdFingerprint;
        }
        if(propertyIndex==5)
        {
            return this.URL!=null?this.URL:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Imagen";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WSQImagen";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Template";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TemplateVersion";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdFingerprint";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "URL";
            info.namespace= "http://casb.bytte.com.co/";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected ProcesoAutenticacionCapturaHuella(android.os.Parcel parcel)
    {
        
        this.Imagen = (byte[])parcel.readValue(null);
        this.WSQImagen = (byte[])parcel.readValue(null);
        this.Template = (String)parcel.readValue(null);
        this.TemplateVersion = (Integer)parcel.readValue(null);
        this.IdFingerprint = (Integer)parcel.readValue(null);
        this.URL = (String)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        
        parcel.writeValue(this.Imagen);
        parcel.writeValue(this.WSQImagen);
        parcel.writeValue(this.Template);
        parcel.writeValue(this.TemplateVersion);
        parcel.writeValue(this.IdFingerprint);
        parcel.writeValue(this.URL);
    }

    public static final Creator< ProcesoAutenticacionCapturaHuella> CREATOR = new Creator< ProcesoAutenticacionCapturaHuella>() {
            @Override
            public ProcesoAutenticacionCapturaHuella createFromParcel(android.os.Parcel in) {
                return new ProcesoAutenticacionCapturaHuella(in);
            }

            @Override
            public ProcesoAutenticacionCapturaHuella[] newArray(int size) {
                return new ProcesoAutenticacionCapturaHuella[size];
            }
        };    
}

