package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ProcesoAutenticacionLogResponse extends Response implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public String IdLog;
    
    public String Version;
    
    public String IdProceso;
    
    public java.util.Date FechaProceso;
    
    public Boolean Ultimo=false;
    
    public String BarCodeBase64;
    
    public Integer StatusFingerprint=0;
    
    public Integer StatusAniOCR=0;
    
    public Integer StatusANIBarCode=0;
    
    public Integer StatusOCRBarCode;
    
    public Integer StatusFace=0;
    
    public Integer StatusDocumento;
    
    public Integer ScoreFingerprintValor;
    
    public Integer ScoreFingerprint;
    
    public Integer ScoreAniOCR;
    
    public Integer ScoreANIBarcode;
    
    public Integer ScoreOCRBarCode;
    
    public Integer ScoreFace;
    
    public Integer ScoreFaceValor;
    
    public Integer ScoreDocumento;
    
    public Boolean Finalizado;
    
    public Boolean AutenticadoDocumento=false;
    
    public String NumeroDocumento;
    
    public ProcesoAutenticacionDocumento ImagenDocumento;
    
    public ArrayOfProcesoAutenticacionCapturaHuella HuellasProceso;
    
    public DocumentoData BarCodeData;
    

    public ProcesoAutenticacionLogResponse()
    {
    }
    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdLog"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdLog = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IdLog = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Version"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Version = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Version = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdProceso"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdProceso = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IdProceso = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaProceso"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaProceso = Helper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.FechaProceso = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Ultimo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Ultimo = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Ultimo = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BarCodeBase64"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BarCodeBase64 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BarCodeBase64 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusFingerprint"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusFingerprint = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusFingerprint = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusAniOCR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusAniOCR = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusAniOCR = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusANIBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusANIBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusANIBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusOCRBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusOCRBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusOCRBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusFace"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusFace = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusFace = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusDocumento = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusDocumento = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFingerprintValor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFingerprintValor = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFingerprintValor = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFingerprint"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFingerprint = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFingerprint = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreAniOCR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreAniOCR = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreAniOCR = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreANIBarcode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreANIBarcode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreANIBarcode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreOCRBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreOCRBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreOCRBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFace"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFace = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFace = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFaceValor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFaceValor = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFaceValor = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreDocumento = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreDocumento = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Finalizado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Finalizado = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Finalizado = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AutenticadoDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AutenticadoDocumento = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AutenticadoDocumento = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ImagenDocumento"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ImagenDocumento = (ProcesoAutenticacionDocumento)__envelope.get(j,ProcesoAutenticacionDocumento.class,false);
            }
            return true;
        }
        if (info.name.equals("HuellasProceso"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)__envelope.get(j,ArrayOfProcesoAutenticacionCapturaHuella.class,false);
            }
            return true;
        }
        if (info.name.equals("BarCodeData"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BarCodeData = (DocumentoData)__envelope.get(j,DocumentoData.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.IdLog!=null?this.IdLog:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.Version!=null?this.Version:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.IdProceso!=null?this.IdProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.FechaProceso!=null?Helper.getDateTimeFormat().format(this.FechaProceso):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return Ultimo;
        }
        if(propertyIndex==count+5)
        {
            return this.BarCodeBase64!=null?this.BarCodeBase64:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+6)
        {
            return StatusFingerprint;
        }
        if(propertyIndex==count+7)
        {
            return StatusAniOCR;
        }
        if(propertyIndex==count+8)
        {
            return StatusANIBarCode;
        }
        if(propertyIndex==count+9)
        {
            return this.StatusOCRBarCode!=null?this.StatusOCRBarCode:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+10)
        {
            return StatusFace;
        }
        if(propertyIndex==count+11)
        {
            return this.StatusDocumento!=null?this.StatusDocumento:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+12)
        {
            return this.ScoreFingerprintValor!=null?this.ScoreFingerprintValor:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+13)
        {
            return this.ScoreFingerprint!=null?this.ScoreFingerprint:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+14)
        {
            return this.ScoreAniOCR!=null?this.ScoreAniOCR:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+15)
        {
            return this.ScoreANIBarcode!=null?this.ScoreANIBarcode:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+16)
        {
            return this.ScoreOCRBarCode!=null?this.ScoreOCRBarCode:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+17)
        {
            return this.ScoreFace!=null?this.ScoreFace:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+18)
        {
            return this.ScoreFaceValor!=null?this.ScoreFaceValor:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+19)
        {
            return this.ScoreDocumento!=null?this.ScoreDocumento:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+20)
        {
            return this.Finalizado!=null?this.Finalizado:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+21)
        {
            return AutenticadoDocumento;
        }
        if(propertyIndex==count+22)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+23)
        {
            return this.ImagenDocumento!=null?this.ImagenDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+24)
        {
            return this.HuellasProceso!=null?this.HuellasProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+25)
        {
            return this.BarCodeData!=null?this.BarCodeData:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+26;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdLog";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Version";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Ultimo";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BarCodeBase64";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusFingerprint";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusAniOCR";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusANIBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusOCRBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+10)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusFace";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+11)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+12)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFingerprintValor";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+13)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFingerprint";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+14)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreAniOCR";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+15)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreANIBarcode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+16)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreOCRBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+17)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFace";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+18)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFaceValor";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+19)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+20)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Finalizado";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+21)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AutenticadoDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+23)
        {
            info.type = ProcesoAutenticacionDocumento.class;
            info.name = "ImagenDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+24)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "HuellasProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+25)
        {
            info.type = DocumentoData.class;
            info.name = "BarCodeData";
            info.namespace= "http://casb.bytte.com.co/";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected ProcesoAutenticacionLogResponse(android.os.Parcel parcel)
    {
        super(parcel);
        this.IdLog = (String)parcel.readValue(null);
        this.Version = (String)parcel.readValue(null);
        this.IdProceso = (String)parcel.readValue(null);
        this.FechaProceso = (java.util.Date)parcel.readValue(null);
        this.Ultimo = (Boolean)parcel.readValue(null);
        this.BarCodeBase64 = (String)parcel.readValue(null);
        this.StatusFingerprint = (Integer)parcel.readValue(null);
        this.StatusAniOCR = (Integer)parcel.readValue(null);
        this.StatusANIBarCode = (Integer)parcel.readValue(null);
        this.StatusOCRBarCode = (Integer)parcel.readValue(null);
        this.StatusFace = (Integer)parcel.readValue(null);
        this.StatusDocumento = (Integer)parcel.readValue(null);
        this.ScoreFingerprintValor = (Integer)parcel.readValue(null);
        this.ScoreFingerprint = (Integer)parcel.readValue(null);
        this.ScoreAniOCR = (Integer)parcel.readValue(null);
        this.ScoreANIBarcode = (Integer)parcel.readValue(null);
        this.ScoreOCRBarCode = (Integer)parcel.readValue(null);
        this.ScoreFace = (Integer)parcel.readValue(null);
        this.ScoreFaceValor = (Integer)parcel.readValue(null);
        this.ScoreDocumento = (Integer)parcel.readValue(null);
        this.Finalizado = (Boolean)parcel.readValue(null);
        this.AutenticadoDocumento = (Boolean)parcel.readValue(null);
        this.NumeroDocumento = (String)parcel.readValue(null);
        this.ImagenDocumento = (ProcesoAutenticacionDocumento)parcel.readValue(this.getClass().getClassLoader());
        this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)parcel.readValue(this.getClass().getClassLoader());
        this.BarCodeData = (DocumentoData)parcel.readValue(this.getClass().getClassLoader());
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        super.writeToParcel(parcel, flags);
        parcel.writeValue(this.IdLog);
        parcel.writeValue(this.Version);
        parcel.writeValue(this.IdProceso);
        parcel.writeValue(this.FechaProceso);
        parcel.writeValue(this.Ultimo);
        parcel.writeValue(this.BarCodeBase64);
        parcel.writeValue(this.StatusFingerprint);
        parcel.writeValue(this.StatusAniOCR);
        parcel.writeValue(this.StatusANIBarCode);
        parcel.writeValue(this.StatusOCRBarCode);
        parcel.writeValue(this.StatusFace);
        parcel.writeValue(this.StatusDocumento);
        parcel.writeValue(this.ScoreFingerprintValor);
        parcel.writeValue(this.ScoreFingerprint);
        parcel.writeValue(this.ScoreAniOCR);
        parcel.writeValue(this.ScoreANIBarcode);
        parcel.writeValue(this.ScoreOCRBarCode);
        parcel.writeValue(this.ScoreFace);
        parcel.writeValue(this.ScoreFaceValor);
        parcel.writeValue(this.ScoreDocumento);
        parcel.writeValue(this.Finalizado);
        parcel.writeValue(this.AutenticadoDocumento);
        parcel.writeValue(this.NumeroDocumento);
        parcel.writeValue(this.ImagenDocumento);
        parcel.writeValue(this.HuellasProceso);
        parcel.writeValue(this.BarCodeData);
    }

    public static final Creator< ProcesoAutenticacionLogResponse> CREATOR = new Creator< ProcesoAutenticacionLogResponse>() {
            @Override
            public ProcesoAutenticacionLogResponse createFromParcel(android.os.Parcel in) {
                return new ProcesoAutenticacionLogResponse(in);
            }

            @Override
            public ProcesoAutenticacionLogResponse[] newArray(int size) {
                return new ProcesoAutenticacionLogResponse[size];
            }
        };    
}

