package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ProcesoValidacionDocumentoResponse extends Response implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public Integer ScoreDactilar=0;
    
    public Integer ScoreDactilarValor=0;
    
    public Integer ScoreANIOCR=0;
    
    public Integer ScoreANIBarCode=0;
    
    public Integer ScoreOCRBarCode=0;
    
    public Integer ScoreFace=0;
    
    public Integer ScoreFaceValor=0;
    
    public Integer ScoreDocumento=0;
    
    public Integer StatusDactilar=0;
    
    public Integer StatusANIOCR=0;
    
    public Integer StatusANIBarCode=0;
    
    public Integer StatusOCRBarCode=0;
    
    public Integer StatusFace=0;
    
    public Integer StatusDocumento=0;
    
    public Boolean AutenticadoDocumento=false;
    

    public ProcesoValidacionDocumentoResponse()
    {
    }
    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ScoreDactilar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreDactilar = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreDactilar = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreDactilarValor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreDactilarValor = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreDactilarValor = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreANIOCR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreANIOCR = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreANIOCR = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreANIBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreANIBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreANIBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreOCRBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreOCRBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreOCRBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFace"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFace = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFace = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreFaceValor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreFaceValor = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreFaceValor = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ScoreDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ScoreDocumento = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ScoreDocumento = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusDactilar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusDactilar = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusDactilar = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusANIOCR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusANIOCR = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusANIOCR = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusANIBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusANIBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusANIBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusOCRBarCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusOCRBarCode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusOCRBarCode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusFace"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusFace = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusFace = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StatusDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StatusDocumento = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.StatusDocumento = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AutenticadoDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AutenticadoDocumento = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AutenticadoDocumento = (Boolean)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ScoreDactilar;
        }
        if(propertyIndex==count+1)
        {
            return ScoreDactilarValor;
        }
        if(propertyIndex==count+2)
        {
            return ScoreANIOCR;
        }
        if(propertyIndex==count+3)
        {
            return ScoreANIBarCode;
        }
        if(propertyIndex==count+4)
        {
            return ScoreOCRBarCode;
        }
        if(propertyIndex==count+5)
        {
            return ScoreFace;
        }
        if(propertyIndex==count+6)
        {
            return ScoreFaceValor;
        }
        if(propertyIndex==count+7)
        {
            return ScoreDocumento;
        }
        if(propertyIndex==count+8)
        {
            return StatusDactilar;
        }
        if(propertyIndex==count+9)
        {
            return StatusANIOCR;
        }
        if(propertyIndex==count+10)
        {
            return StatusANIBarCode;
        }
        if(propertyIndex==count+11)
        {
            return StatusOCRBarCode;
        }
        if(propertyIndex==count+12)
        {
            return StatusFace;
        }
        if(propertyIndex==count+13)
        {
            return StatusDocumento;
        }
        if(propertyIndex==count+14)
        {
            return AutenticadoDocumento;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+15;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreDactilar";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreDactilarValor";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreANIOCR";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreANIBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreOCRBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFace";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreFaceValor";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScoreDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusDactilar";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusANIOCR";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+10)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusANIBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+11)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusOCRBarCode";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+12)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusFace";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+13)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "StatusDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+14)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AutenticadoDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected ProcesoValidacionDocumentoResponse(android.os.Parcel parcel)
    {
        super(parcel);
        this.ScoreDactilar = (Integer)parcel.readValue(null);
        this.ScoreDactilarValor = (Integer)parcel.readValue(null);
        this.ScoreANIOCR = (Integer)parcel.readValue(null);
        this.ScoreANIBarCode = (Integer)parcel.readValue(null);
        this.ScoreOCRBarCode = (Integer)parcel.readValue(null);
        this.ScoreFace = (Integer)parcel.readValue(null);
        this.ScoreFaceValor = (Integer)parcel.readValue(null);
        this.ScoreDocumento = (Integer)parcel.readValue(null);
        this.StatusDactilar = (Integer)parcel.readValue(null);
        this.StatusANIOCR = (Integer)parcel.readValue(null);
        this.StatusANIBarCode = (Integer)parcel.readValue(null);
        this.StatusOCRBarCode = (Integer)parcel.readValue(null);
        this.StatusFace = (Integer)parcel.readValue(null);
        this.StatusDocumento = (Integer)parcel.readValue(null);
        this.AutenticadoDocumento = (Boolean)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        super.writeToParcel(parcel, flags);
        parcel.writeValue(this.ScoreDactilar);
        parcel.writeValue(this.ScoreDactilarValor);
        parcel.writeValue(this.ScoreANIOCR);
        parcel.writeValue(this.ScoreANIBarCode);
        parcel.writeValue(this.ScoreOCRBarCode);
        parcel.writeValue(this.ScoreFace);
        parcel.writeValue(this.ScoreFaceValor);
        parcel.writeValue(this.ScoreDocumento);
        parcel.writeValue(this.StatusDactilar);
        parcel.writeValue(this.StatusANIOCR);
        parcel.writeValue(this.StatusANIBarCode);
        parcel.writeValue(this.StatusOCRBarCode);
        parcel.writeValue(this.StatusFace);
        parcel.writeValue(this.StatusDocumento);
        parcel.writeValue(this.AutenticadoDocumento);
    }

    public static final Creator< ProcesoValidacionDocumentoResponse> CREATOR = new Creator< ProcesoValidacionDocumentoResponse>() {
            @Override
            public ProcesoValidacionDocumentoResponse createFromParcel(android.os.Parcel in) {
                return new ProcesoValidacionDocumentoResponse(in);
            }

            @Override
            public ProcesoValidacionDocumentoResponse[] newArray(int size) {
                return new ProcesoValidacionDocumentoResponse[size];
            }
        };    
}

