package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RequestBase extends AttributeContainer implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public String IdentificadorConsumidor;
    
    public String IdentificadorProceso;
    
    public String ImageKey;
    
    public String NumeroDocumento;
    private transient java.lang.Object __source;    
    

    public RequestBase()
    {
    }
    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdentificadorConsumidor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdentificadorConsumidor = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IdentificadorConsumidor = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdentificadorProceso"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdentificadorProceso = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IdentificadorProceso = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ImageKey"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ImageKey = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ImageKey = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdentificadorConsumidor!=null?this.IdentificadorConsumidor:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IdentificadorProceso!=null?this.IdentificadorProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ImageKey!=null?this.ImageKey:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdentificadorConsumidor";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdentificadorProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ImageKey";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://casb.bytte.com.co/";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected RequestBase(android.os.Parcel parcel)
    {
        
        this.IdentificadorConsumidor = (String)parcel.readValue(null);
        this.IdentificadorProceso = (String)parcel.readValue(null);
        this.ImageKey = (String)parcel.readValue(null);
        this.NumeroDocumento = (String)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        
        parcel.writeValue(this.IdentificadorConsumidor);
        parcel.writeValue(this.IdentificadorProceso);
        parcel.writeValue(this.ImageKey);
        parcel.writeValue(this.NumeroDocumento);
    }

    public static final Creator< RequestBase> CREATOR = new Creator< RequestBase>() {
            @Override
            public RequestBase createFromParcel(android.os.Parcel in) {
                return new RequestBase(in);
            }

            @Override
            public RequestBase[] newArray(int size) {
                return new RequestBase[size];
            }
        };    
}

