package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Response extends AttributeContainer implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public Boolean OperacionExitosa=false;
    
    public String Mensaje;
    
    public String MensajeOperacion;
    private transient java.lang.Object __source;    
    

    public Response()
    {
    }
    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("OperacionExitosa"))
        {	
            java.lang.Object j = inObj.getAttribute("OperacionExitosa");
            if (j != null)
            {
                OperacionExitosa = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("Mensaje"))
        {	
            java.lang.Object j = inObj.getAttribute("Mensaje");
            if (j != null)
            {
                Mensaje = j.toString();
            }
        }
        if (inObj.hasAttribute("MensajeOperacion"))
        {	
            java.lang.Object j = inObj.getAttribute("MensajeOperacion");
            if (j != null)
            {
                MensajeOperacion = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "OperacionExitosa";
            info.namespace= "";
            if(this.OperacionExitosa!=null)
            {
                info.setValue(this.OperacionExitosa);
            }
            
        }
        if(index==1)
        {
            info.name = "Mensaje";
            info.namespace= "";
            if(this.Mensaje!=null)
            {
                info.setValue(this.Mensaje);
            }
            
        }
        if(index==2)
        {
            info.name = "MensajeOperacion";
            info.namespace= "";
            if(this.MensajeOperacion!=null)
            {
                info.setValue(this.MensajeOperacion);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }

    protected Response(android.os.Parcel parcel)
    {
        
        this.OperacionExitosa = (Boolean)parcel.readValue(null);
        this.Mensaje = (String)parcel.readValue(null);
        this.MensajeOperacion = (String)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        
        parcel.writeValue(this.OperacionExitosa);
        parcel.writeValue(this.Mensaje);
        parcel.writeValue(this.MensajeOperacion);
    }

    public static final Creator< Response> CREATOR = new Creator< Response>() {
            @Override
            public Response createFromParcel(android.os.Parcel in) {
                return new Response(in);
            }

            @Override
            public Response[] newArray(int size) {
                return new Response[size];
            }
        };    
}

