package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class UsuarioEnrolamiento extends Usuario implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public Boolean EnroladoDactilar=false;
    
    public String TemplateDactilar;
    
    public Boolean EnroladoFacial=false;
    
    public String TemplateFacial;
    

    public UsuarioEnrolamiento()
    {
    }
    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("EnroladoDactilar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EnroladoDactilar = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.EnroladoDactilar = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TemplateDactilar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TemplateDactilar = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TemplateDactilar = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EnroladoFacial"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EnroladoFacial = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.EnroladoFacial = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TemplateFacial"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TemplateFacial = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TemplateFacial = (String)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return EnroladoDactilar;
        }
        if(propertyIndex==count+1)
        {
            return this.TemplateDactilar!=null?this.TemplateDactilar:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return EnroladoFacial;
        }
        if(propertyIndex==count+3)
        {
            return this.TemplateFacial!=null?this.TemplateFacial:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EnroladoDactilar";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TemplateDactilar";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EnroladoFacial";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TemplateFacial";
            info.namespace= "http://casb.bytte.com.co/";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected UsuarioEnrolamiento(android.os.Parcel parcel)
    {
        super(parcel);
        this.EnroladoDactilar = (Boolean)parcel.readValue(null);
        this.TemplateDactilar = (String)parcel.readValue(null);
        this.EnroladoFacial = (Boolean)parcel.readValue(null);
        this.TemplateFacial = (String)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        super.writeToParcel(parcel, flags);
        parcel.writeValue(this.EnroladoDactilar);
        parcel.writeValue(this.TemplateDactilar);
        parcel.writeValue(this.EnroladoFacial);
        parcel.writeValue(this.TemplateFacial);
    }

    public static final Creator< UsuarioEnrolamiento> CREATOR = new Creator< UsuarioEnrolamiento>() {
            @Override
            public UsuarioEnrolamiento createFromParcel(android.os.Parcel in) {
                return new UsuarioEnrolamiento(in);
            }

            @Override
            public UsuarioEnrolamiento[] newArray(int size) {
                return new UsuarioEnrolamiento[size];
            }
        };    
}

