package com.trantec.yo.services.bytte.authentication;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.1.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ValidacionEnrolamientoDocumentoRequest extends RequestBase implements KvmSerializable,java.io.Serializable,android.os.Parcelable
{

    
    public Boolean Completo=false;
    
    public Boolean SoloMinucia=false;
    
    public String BarCodeBase64;
    
    public byte[] ImagenReverso;

    public byte[] ImagenFrente;

    public ArrayOfProcesoAutenticacionCapturaHuella HuellasProceso;
    
    public ScoreRequest ScoreProceso;
    
    public Integer HuellasAProcesar=0;
//    public String IdentificadorProceso;
    

    public ValidacionEnrolamientoDocumentoRequest()
    {
    }
    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Completo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Completo = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Completo = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SoloMinucia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SoloMinucia = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SoloMinucia = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BarCodeBase64"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BarCodeBase64 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BarCodeBase64 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ImagenReverso"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ImagenReverso = Helper.getBinary(j,false);
            }
            return true;
        }
        if (info.name.equals("ImagenFrente"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ImagenFrente = Helper.getBinary(j,false);
            }
            return true;
        }
        if (info.name.equals("HuellasProceso"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)__envelope.get(j,ArrayOfProcesoAutenticacionCapturaHuella.class,false);
            }
            return true;
        }
        if (info.name.equals("ScoreProceso"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ScoreProceso = (ScoreRequest)__envelope.get(j,ScoreRequest.class,false);
            }
            return true;
        }
        if (info.name.equals("HuellasAProcesar"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.HuellasAProcesar = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.HuellasAProcesar = (Integer)obj;
                }
            }
            return true;
        }
//        if (info.name.equals("IdentificadorProceso"))
//        {
//            if(obj!=null)
//            {
//                if (obj.getClass().equals(SoapPrimitive.class))
//                {
//                    SoapPrimitive j =(SoapPrimitive) obj;
//                    if(j.toString()!=null)
//                    {
//                        this.IdentificadorProceso = j.toString();
//                    }
//                }
//                else if (obj instanceof String){
//                    this.IdentificadorProceso = (String)obj;
//                }
//            }
//            return true;
//        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return Completo;
        }
        if(propertyIndex==count+1)
        {
            return SoloMinucia;
        }
        if(propertyIndex==count+2)
        {
            return this.BarCodeBase64!=null?this.BarCodeBase64:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.ImagenReverso!=null?org.kobjects.base64.Base64.encode((byte[])this.ImagenReverso):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.ImagenFrente!=null?org.kobjects.base64.Base64.encode((byte[])this.ImagenFrente):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.HuellasProceso!=null?this.HuellasProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+6)
        {
            return this.ScoreProceso!=null?this.ScoreProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+7)
        {
            return HuellasAProcesar;
        }

//        if(propertyIndex==count+8)
//        {
//            return IdentificadorProceso;
//        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Completo";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SoloMinucia";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BarCodeBase64";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ImagenReverso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ImagenFrente";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "HuellasProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+6)
        {
            info.type = ScoreRequest.class;
            info.name = "ScoreProceso";
            info.namespace= "http://casb.bytte.com.co/";
        }
        if(propertyIndex==count+7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "HuellasAProcesar";
            info.namespace= "http://casb.bytte.com.co/";
        }
//        if(propertyIndex==count+8)
//        {
//            info.type = PropertyInfo.STRING_CLASS;
//            info.name = "IdentificadorProceso";
//            info.namespace= "http://casb.bytte.com.co/";
//        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    protected ValidacionEnrolamientoDocumentoRequest(android.os.Parcel parcel)
    {
        super(parcel);
        this.Completo = (Boolean)parcel.readValue(null);
        this.SoloMinucia = (Boolean)parcel.readValue(null);
        this.BarCodeBase64 = (String)parcel.readValue(null);
        this.ImagenReverso = (byte[])parcel.readValue(null);
        this.ImagenFrente = (byte[])parcel.readValue(null);
        this.HuellasProceso = (ArrayOfProcesoAutenticacionCapturaHuella)parcel.readValue(this.getClass().getClassLoader());
        this.ScoreProceso = (ScoreRequest)parcel.readValue(this.getClass().getClassLoader());
        this.HuellasAProcesar = (Integer)parcel.readValue(null);
//        this.IdentificadorProceso = (String)parcel.readValue(null);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel, int flags) {
        
        super.writeToParcel(parcel, flags);
        parcel.writeValue(this.Completo);
        parcel.writeValue(this.SoloMinucia);
        parcel.writeValue(this.BarCodeBase64);
        parcel.writeValue(this.ImagenReverso);
        parcel.writeValue(this.ImagenFrente);
        parcel.writeValue(this.HuellasProceso);
        parcel.writeValue(this.ScoreProceso);
        parcel.writeValue(this.HuellasAProcesar);
//        parcel.writeValue(this.IdentificadorProceso);
    }

    public static final Creator< ValidacionEnrolamientoDocumentoRequest> CREATOR = new Creator< ValidacionEnrolamientoDocumentoRequest>() {
            @Override
            public ValidacionEnrolamientoDocumentoRequest createFromParcel(android.os.Parcel in) {
                return new ValidacionEnrolamientoDocumentoRequest(in);
            }

            @Override
            public ValidacionEnrolamientoDocumentoRequest[] newArray(int size) {
                return new ValidacionEnrolamientoDocumentoRequest[size];
            }
        };    
}

